### ISSUE TITLE
Documentation for use in Nuxt

### ISSUE THREAD

**Issue by roja** [brillout/wildcard-api#1] opened 2019-01-12 21:58 UTC
Have attempted to use wildcard in Nuxt but am stumbling into an assert 

    validateArgs@109:14

The library seems to think that it's being run within the browser prehaps?

Heres how wildcard is initalised in the nuxt server (using express)

     app.all('/wildcard/*' , async (req, res, next) => {
        const {body, statusCode} = await getApiResponse(req);
        res.status(statusCode);
        res.send(body);
        next();
      });

Heres the endpoint definition:

    const {endpoints} = require('wildcard-api');
    
    endpoints.meaningOfLife = async function () {
      return Date.now();
    };

Heres the script section of the vue component:
 
    <script>
    import {endpoints} from 'wildcard-api/client';
    
    export default {
      async asyncData ({req}) {
        let {meaningOfLife} = endpoints;
    
        if( process.server ) meaningOfLife = meaningOfLife.bind(req.headers);
    
        const theMeaning = await meaningOfLife();
    
        return   {
          theMeaning,
        }
      }
    }
    </script>

Any pointers would be appreciated. Would be useful documentation for others also.

**Comment by roja** [comment] 2019-01-12 23:10
I did some further investigation and the issue is that 

    global.__globalWildcardApi

isn't available from within the components. I have tried to inject it into the context object passed through to the components however it doesn't seem to be available from within plugins either (the most common mechanic to inject things into the context object.)

**Comment by brillout** [comment] 2019-01-13 13:21
Does the component code and the express code run in the same Node.js process?

**Comment by brillout** [comment] 2019-01-13 13:50
By setting `global.hello = 42` in the express code, does running `console.log(global.hello)` in the component code print `42`?

**Comment by brillout** [comment] 2019-01-13 14:01
Is the code online somewhere? I can have a look myself

**Comment by roja** [comment] 2019-01-13 14:11
I have raised a question with the nuxt guys about access to the global object.

**Comment by roja** [comment] 2019-01-13 14:13
Sorry I don’t have the code online but it’s trivial to reproduce. It’s a starter nuxt app using express as the server. I then tried to add wildcard to it.

**Comment by brillout** [comment] 2019-01-13 15:12
I just scaffolded a Nuxt app and added your `meaningOfLife` endpoint and it works.

`await endpoints.meaningOfLife.bind(req)()` successfully returns the `new Date()` value when run on the server and `await endpoints.meaningOfLife()` returns the value when run in the browser.

What does `console.log(global.__globalWildcardApi)` print when run before `await endpoints.meaningOfLife.bind(req)()`? In my case it correctly prints the global `WildcardApi` instance.

Note that GitHub has free private repos in case that's an option for you to trust me with your code.

**Comment by roja** [comment] 2019-01-13 16:06
Oh, how odd.

Let me get the code online (no trust issue, just didn’t have it online)

Thanks for investigating, how irritating if I have wasted your time with something trivial! Will try and get back ASAP.

**Comment by roja** [comment] 2019-01-13 17:12
> I just scaffolded a Nuxt app and added your `meaningOfLife` endpoint and it works.
> 
> `await endpoints.meaningOfLife.bind(req)()` successfully returns the `new Date()` value when run on the server and `await endpoints.meaningOfLife()` returns the value when run in the browser.
> 
> What does `console.log(global.__globalWildcardApi)` print when run before `await endpoints.meaningOfLife.bind(req)()`? In my case it correctly prints the global `WildcardApi` instance.
> 
> Note that GitHub has free private repos in case that's an option for you to trust me with your code.

Could you share your working code also?

**Comment by roja** [comment] 2019-01-13 19:37
Here is the code:

https://github.com/roja/nuxt-wildcard

Still seems to be broken but it's likely because I am missing something obvious!

Cloning that repo then running

    yarn install
    yarn dev

and navigating to

    http://127.0.0.1:3000/

gives me the `"Wrong SSR usage."` error

**Comment by brillout** [comment] 2019-01-13 21:06
Weird, when I run your code I don't get `Wrong SSR usage`.

I do get an error though: `Endpoint meaningOfLife doesn't exist.` which I fixed by adding `require('./endpoints/first_endpoint');` to your server entry `./server/index.js`. (Otherwise your module defining the endpoint will never load.)

Once I did that, everything worked.

> how irritating if I have wasted your time with something trivial

No probs, everyone makes trivial mistakes^^.

**Comment by roja** [comment] 2019-01-13 21:06
Solved it!

I never require the endpoints which somehow results in that assert being thrown. Not entirely sure why but by requiring the endpoints the problem goes away.

A simple change in the assert code should put people on the right track!

**Comment by brillout** [comment] 2019-01-13 21:12
See my comment I posted at the same time than you^^.

Yea that's weird that you got another error message than me.

I'm closing this ticket as I can't reproduce the wrong error message, if that's ok with you.

Let me know what you think of Wildcard once you used it a while. Would be awesome:)

You opened the first issue btw!

**Closed by brillout** 2019-01-13 21:12 UTC

**Comment by roja** [comment] 2019-01-13 22:53
It may help someone in the future that the inclusion of:

    next()

in the 

     app.all('/wildcard/*' , async (req, res, next) => {
        const {body, statusCode} = await getApiResponse(req);
        res.status(statusCode);
        res.send(body);
        next();
      });

also caused issues. simply removing it fixed them.

**Comment by brillout** [comment] 2019-05-09 20:32
@roja I removed all `next()` calls from the documentation. You're right, it's a saner default to not call `next()`.

Do you still use Wildcard? If not, what made you stop using Wildcard?
